### ISSUE TITLE
Dropped Xdebug

### ISSUE THREAD

**Issue by zweishar** [droath/project-x#21]
I just tried setting up a new `project-x` based project by following the instructions in `istop-ng`. It looks like `xdebug` support may have been dropped at some point between `project-x` `0.1.8` and `0.2.0`. `phpinfo()` confirms that it was not installed, although many of the `xdebug` related environment variables are still being set.

I know this is working in `0.1.8`, can you reproduce this issue? If you can't then I can tear down my project and run through set up tasks again to double check.

**Comment by droath** [comment]
I've done a rebuild and I can confirm that `xdebug` is being added to the docker build file for PHP. Also I've rendered out the PHPinfo, as you can see it's been initialized: 
![screen shot 2017-04-30 at 7 24 36 pm](https://cloud.githubusercontent.com/assets/371104/25569830/f09907d2-2dda-11e7-8046-bc2071577023.png)

**Comment by zweishar** [comment]
This appears to have been an underlying issue with Docker and the way it deals with images. I had an old image without xdebug on my machine with the same name as the new one I was trying create. Instead of tearing down the old one and rebuilding, Docker used the old image. Remove the old image and allowing docker to rebuild solved the problem.
