### ISSUE TITLE
Set host IP address dynamically on startup

### ISSUE THREAD

**Issue by zweishar** [droath/project-x#23]
Currently project-x writes the host IP address to `docker-compose-dev.yml` on project setup. This is not ideal because we commit `docker-compose-dev.yml` to version control when working on a project and IP addresses can't be relied upon like that.

Establish the host IP address as an environment variable on `engine:up` so that it works even after your IP address has changed.

**Comment by droath** [comment]
Sorry, committed something on the wrong issue number... :) Please disregard.

**Comment by zweishar** [comment]
The tests are failing on [this line](https://github.com/droath/project-x/blob/master/tests/Engine/DockerEngineTypeTest.php#L51-L52). This test case isn't really applicable now because we're not writing to the `docker-compose-dev.yml` any longer.

Do you know if it's possible to access values of a docker container from phpunit? If so we could test that the host ip variable is getting set in the container and that it matches the host machine. Otherwise I think we may just need to remove this test case.

**Comment by droath** [comment]
@zweishar That makes sense. I've removed the PHPunit test for now, I think we'll need to maybe add a functional test later on, once its been setup. ;) I'm really not sure how this is working, I'm kind of baffled by it. Let me do some local testing to see how this works.

**Comment by zweishar** [comment]
@droath It's working based on the ability of docker compose files to sub environment variables at run time. You can read more about it here: https://docs.docker.com/compose/environment-variables/

**Comment by zweishar** [comment]
Change approach to store environment variables in .env file, this file should be ignored from projects. The .env file needs to be written / updated every time we run `engine:up`. Update the gitignore template to ignore `.env` file.
