### ISSUE TITLE
Drupal .gitignore file is overzealous

### ISSUE THREAD

**Issue by remydenton** [droath/project-x#35]
We had a project that ran into a problem because the theme had a required file named `console` that was ignored by [the line "console"](https://github.com/droath/project-x/blob/master/templates/drupal/.gitignore.txt#L138) in the base .gitignore.

I see a number of other lines that are overly specific or redundant.  Some examples:

- [reports](https://github.com/droath/project-x/blob/master/templates/drupal/.gitignore.txt#L34) would ignore any file or directory anywhere named "reports".  Doesn't seem that outlandish.
- [tmp](https://github.com/droath/project-x/blob/master/templates/drupal/.gitignore.txt#L33) and [tmp/**](https://github.com/droath/project-x/blob/master/templates/drupal/.gitignore.txt#L62) are redundant.  The first also isn't specific enough.

Where did this .gitignore file come from?  It looks like it was added all at once in 16e9fff.  Seems like we should open an issue against the original source as well.

**Comment by benjifisher** [comment]
@marvil07 tracked it down to one of the BLT template files:  https://github.com/acquia/blt/blob/8.x/template/.gitignore#L128

He opened an issue on the BLT issues queue:  https://github.com/acquia/blt/issues/1727

**Comment by remydenton** [comment]
That line's not even relevant anymore!?  Thanks, Acquia...

**Comment by droath** [comment]
Fixed in release 2.2.17.
