### ISSUE TITLE
Streamline drush executing from within the docker container. 

### ISSUE THREAD

**Issue by droath** [droath/project-x#46]
`docker exec [CONTAINER] /var/www/html/vendor/bin/drush`

This is hard to remember, so it would be nice to streamline this within the project-x command.

**Comment by zweishar** [comment]
Do you think it's possible to have `project-x` delegate commands to the container to make this easier to remember? I recently installed [lando](https://github.com/lando/lando) and they use a model like this: `lando drush your-drush-command` to abstract that complexity away from the user.

**Comment by droath** [comment]
Yes that's what I was thinking it would function like. I'm thinking we'll have one for drush (`project-x drupal:drush [command]`) and another for composer (`project-x php:composer [command]`). As both of these commands should be ran within the docker container.

**Comment by droath** [comment]
Added in 2.3.0
