### ISSUE TITLE
Use composer install on deploy

### ISSUE THREAD

**Issue by marvil07** [droath/project-x#69]
The current behavior is triggering `composer update` during deploy.

I think what is intended is to deploy a known version, i.e. what is running locally.
This may be different for projects not tracking `composer.lock`, but even in that case `composer install` will trigger the `composer.lock` generation. 

Because of this I think the command to run during deploy is `composer install` instead.

**Comment by droath** [comment]
@marvil07 
Yes `composer update` is ran during the deployment. This is only to address any conflicts with the `content-hash` having a mismatch. It does not update any packages at this time. As we're passing the `--lock` flag. Which will only update the `composer.lock` file if something wasn't correctly done in the composer file in the root of the project.

https://github.com/droath/project-x/blob/master/src/Project/PhpProjectType.php#L293

**Comment by marvil07** [comment]
@droath Makes sense, thanks for the explanation.
